# Generated by Django 4.2.1 on 2024-01-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_pagina', '0003_formulariopersonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariopersonas',
            name='linkedin_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
